### ISSUE TITLE
when user downloaded mp3 file, the http 406 error has occurred

### ISSUE THREAD

**Issue by Evan2698** [xi2/httpgzip#2]
I take a snapshot as blew .  chrome browser 74 
I found this code [`fragment:`]

[`   

               encs := acceptedEncodings(r)
		// return if no acceptable encodings
		if len(encs) == 0 {
			w.WriteHeader(http.StatusNotAcceptable)
			return
		}

`]                 

snapshot:  (https://s2.ax1x.com/2019/05/06/EDFTdx.png)

**Comment by xi2** [comment]
Thank you for your bug report. I have hopefully fixed this issue now, which was bad parsing of the Accept-Encoding header. Let me know if you still have an issue.

**Comment by Evan2698** [comment]
you are too awesome. I've reviewed your code already.

**Comment by Evan2698** [comment]
thanks a lot !

**Comment by xi2** [comment]
I have pushed one more commit to fix the tests.
